development:
  adapter: postgresql
  encoding: unicode
  database: producty_development
  username: TheDandersons
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: producty_test
  password:


production:
  adapter: postgresql
  database: producty
  username: producty
  password:
  host:
