development:
  adapter: postgresql
  encoding: unicode
  database: producty_development
  username: postgres
  password:
  host: localhost



production:
  adapter: postgresql
  database: producty
  username: producty
  password:
  host:
