development:
  adapter: postgresql
  encoding: unicode
  database: producty_development
  pool: 5
  username: producty
  password:



production:
  adapter: postgresql
  database: producty
  username: producty
  password:
  host:
